// ActivityLogModel — admin-side audit trail.
//
// Stored in `activityLogs/{logId}` collection. Every admin-side
// mutation (approve / revoke / suspend / reactivate / category
// CRUD / dispute resolution) and every key buyer/seller event
// (registration / login / order status change) writes a doc here.
//
// Writes are best-effort: callers MUST wrap `write(...)` in
// try/catch + AppLogger.warning so a failed audit write never
// breaks the user-visible flow (login, ordering, etc.).

import 'package:freezed_annotation/freezed_annotation.dart';

import '../utils/timestamp_converter.dart';

part 'activity_log_model.freezed.dart';
part 'activity_log_model.g.dart';

/// What kind of event produced this log entry. Stored as a string
/// in the `type` field so existing docs survive enum reshuffles.
enum ActivityLogType {
  login,
  registration,
  adminAction,
  orderStatus,
  listingModeration,
  disputeResolution,
  categoryChange,
}

@freezed
class ActivityLogModel with _$ActivityLogModel {
  const factory ActivityLogModel({
    /// Document id (auto-generated by Firestore `.add()`).
    required String logId,

    /// One of [ActivityLogType] names. Stored as a string so the
    /// schema is forward-compatible with future types.
    required String type,

    /// Uid of the user that performed the action. For self-service
    /// events (login, registration) this is the user themselves.
    String? actorUid,

    /// "buyer" / "streetSeller" / "admin" — denormalised so the
    /// Activity Logs screen can filter without a join.
    String? actorRole,

    /// "user" / "order" / "listing" / "category" — what the action
    /// touched.
    String? targetType,

    /// Id of the affected target.
    String? targetId,

    /// Human-readable headline shown on the Activity Logs screen.
    required String title,

    /// One-line subtitle shown below the title.
    String? subtitle,

    /// Free-form metadata bag for the Admin Logs detail sheet.
    /// Always optional so old docs without it still deserialize.
    Map<String, dynamic>? metadata,

    @TimestampConverter() required DateTime createdAt,
  }) = _ActivityLogModel;

  factory ActivityLogModel.fromJson(Map<String, dynamic> json) =>
      _$ActivityLogModelFromJson(json);
}
