// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'activity_log_model.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

ActivityLogModel _$ActivityLogModelFromJson(Map<String, dynamic> json) {
  return _ActivityLogModel.fromJson(json);
}

/// @nodoc
mixin _$ActivityLogModel {
  /// Document id (auto-generated by Firestore `.add()`).
  String get logId => throw _privateConstructorUsedError;

  /// One of [ActivityLogType] names. Stored as a string so the
  /// schema is forward-compatible with future types.
  String get type => throw _privateConstructorUsedError;

  /// Uid of the user that performed the action. For self-service
  /// events (login, registration) this is the user themselves.
  String? get actorUid => throw _privateConstructorUsedError;

  /// "buyer" / "streetSeller" / "admin" — denormalised so the
  /// Activity Logs screen can filter without a join.
  String? get actorRole => throw _privateConstructorUsedError;

  /// "user" / "order" / "listing" / "category" — what the action
  /// touched.
  String? get targetType => throw _privateConstructorUsedError;

  /// Id of the affected target.
  String? get targetId => throw _privateConstructorUsedError;

  /// Human-readable headline shown on the Activity Logs screen.
  String get title => throw _privateConstructorUsedError;

  /// One-line subtitle shown below the title.
  String? get subtitle => throw _privateConstructorUsedError;

  /// Free-form metadata bag for the Admin Logs detail sheet.
  /// Always optional so old docs without it still deserialize.
  Map<String, dynamic>? get metadata => throw _privateConstructorUsedError;
  @TimestampConverter()
  DateTime get createdAt => throw _privateConstructorUsedError;

  /// Serializes this ActivityLogModel to a JSON map.
  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;

  /// Create a copy of ActivityLogModel
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  $ActivityLogModelCopyWith<ActivityLogModel> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $ActivityLogModelCopyWith<$Res> {
  factory $ActivityLogModelCopyWith(
          ActivityLogModel value, $Res Function(ActivityLogModel) then) =
      _$ActivityLogModelCopyWithImpl<$Res, ActivityLogModel>;
  @useResult
  $Res call(
      {String logId,
      String type,
      String? actorUid,
      String? actorRole,
      String? targetType,
      String? targetId,
      String title,
      String? subtitle,
      Map<String, dynamic>? metadata,
      @TimestampConverter() DateTime createdAt});
}

/// @nodoc
class _$ActivityLogModelCopyWithImpl<$Res, $Val extends ActivityLogModel>
    implements $ActivityLogModelCopyWith<$Res> {
  _$ActivityLogModelCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  /// Create a copy of ActivityLogModel
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? logId = null,
    Object? type = null,
    Object? actorUid = freezed,
    Object? actorRole = freezed,
    Object? targetType = freezed,
    Object? targetId = freezed,
    Object? title = null,
    Object? subtitle = freezed,
    Object? metadata = freezed,
    Object? createdAt = null,
  }) {
    return _then(_value.copyWith(
      logId: null == logId
          ? _value.logId
          : logId // ignore: cast_nullable_to_non_nullable
              as String,
      type: null == type
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
      actorUid: freezed == actorUid
          ? _value.actorUid
          : actorUid // ignore: cast_nullable_to_non_nullable
              as String?,
      actorRole: freezed == actorRole
          ? _value.actorRole
          : actorRole // ignore: cast_nullable_to_non_nullable
              as String?,
      targetType: freezed == targetType
          ? _value.targetType
          : targetType // ignore: cast_nullable_to_non_nullable
              as String?,
      targetId: freezed == targetId
          ? _value.targetId
          : targetId // ignore: cast_nullable_to_non_nullable
              as String?,
      title: null == title
          ? _value.title
          : title // ignore: cast_nullable_to_non_nullable
              as String,
      subtitle: freezed == subtitle
          ? _value.subtitle
          : subtitle // ignore: cast_nullable_to_non_nullable
              as String?,
      metadata: freezed == metadata
          ? _value.metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      createdAt: null == createdAt
          ? _value.createdAt
          : createdAt // ignore: cast_nullable_to_non_nullable
              as DateTime,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$ActivityLogModelImplCopyWith<$Res>
    implements $ActivityLogModelCopyWith<$Res> {
  factory _$$ActivityLogModelImplCopyWith(_$ActivityLogModelImpl value,
          $Res Function(_$ActivityLogModelImpl) then) =
      __$$ActivityLogModelImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {String logId,
      String type,
      String? actorUid,
      String? actorRole,
      String? targetType,
      String? targetId,
      String title,
      String? subtitle,
      Map<String, dynamic>? metadata,
      @TimestampConverter() DateTime createdAt});
}

/// @nodoc
class __$$ActivityLogModelImplCopyWithImpl<$Res>
    extends _$ActivityLogModelCopyWithImpl<$Res, _$ActivityLogModelImpl>
    implements _$$ActivityLogModelImplCopyWith<$Res> {
  __$$ActivityLogModelImplCopyWithImpl(_$ActivityLogModelImpl _value,
      $Res Function(_$ActivityLogModelImpl) _then)
      : super(_value, _then);

  /// Create a copy of ActivityLogModel
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? logId = null,
    Object? type = null,
    Object? actorUid = freezed,
    Object? actorRole = freezed,
    Object? targetType = freezed,
    Object? targetId = freezed,
    Object? title = null,
    Object? subtitle = freezed,
    Object? metadata = freezed,
    Object? createdAt = null,
  }) {
    return _then(_$ActivityLogModelImpl(
      logId: null == logId
          ? _value.logId
          : logId // ignore: cast_nullable_to_non_nullable
              as String,
      type: null == type
          ? _value.type
          : type // ignore: cast_nullable_to_non_nullable
              as String,
      actorUid: freezed == actorUid
          ? _value.actorUid
          : actorUid // ignore: cast_nullable_to_non_nullable
              as String?,
      actorRole: freezed == actorRole
          ? _value.actorRole
          : actorRole // ignore: cast_nullable_to_non_nullable
              as String?,
      targetType: freezed == targetType
          ? _value.targetType
          : targetType // ignore: cast_nullable_to_non_nullable
              as String?,
      targetId: freezed == targetId
          ? _value.targetId
          : targetId // ignore: cast_nullable_to_non_nullable
              as String?,
      title: null == title
          ? _value.title
          : title // ignore: cast_nullable_to_non_nullable
              as String,
      subtitle: freezed == subtitle
          ? _value.subtitle
          : subtitle // ignore: cast_nullable_to_non_nullable
              as String?,
      metadata: freezed == metadata
          ? _value._metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      createdAt: null == createdAt
          ? _value.createdAt
          : createdAt // ignore: cast_nullable_to_non_nullable
              as DateTime,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$ActivityLogModelImpl implements _ActivityLogModel {
  const _$ActivityLogModelImpl(
      {required this.logId,
      required this.type,
      this.actorUid,
      this.actorRole,
      this.targetType,
      this.targetId,
      required this.title,
      this.subtitle,
      final Map<String, dynamic>? metadata,
      @TimestampConverter() required this.createdAt})
      : _metadata = metadata;

  factory _$ActivityLogModelImpl.fromJson(Map<String, dynamic> json) =>
      _$$ActivityLogModelImplFromJson(json);

  /// Document id (auto-generated by Firestore `.add()`).
  @override
  final String logId;

  /// One of [ActivityLogType] names. Stored as a string so the
  /// schema is forward-compatible with future types.
  @override
  final String type;

  /// Uid of the user that performed the action. For self-service
  /// events (login, registration) this is the user themselves.
  @override
  final String? actorUid;

  /// "buyer" / "streetSeller" / "admin" — denormalised so the
  /// Activity Logs screen can filter without a join.
  @override
  final String? actorRole;

  /// "user" / "order" / "listing" / "category" — what the action
  /// touched.
  @override
  final String? targetType;

  /// Id of the affected target.
  @override
  final String? targetId;

  /// Human-readable headline shown on the Activity Logs screen.
  @override
  final String title;

  /// One-line subtitle shown below the title.
  @override
  final String? subtitle;

  /// Free-form metadata bag for the Admin Logs detail sheet.
  /// Always optional so old docs without it still deserialize.
  final Map<String, dynamic>? _metadata;

  /// Free-form metadata bag for the Admin Logs detail sheet.
  /// Always optional so old docs without it still deserialize.
  @override
  Map<String, dynamic>? get metadata {
    final value = _metadata;
    if (value == null) return null;
    if (_metadata is EqualUnmodifiableMapView) return _metadata;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableMapView(value);
  }

  @override
  @TimestampConverter()
  final DateTime createdAt;

  @override
  String toString() {
    return 'ActivityLogModel(logId: $logId, type: $type, actorUid: $actorUid, actorRole: $actorRole, targetType: $targetType, targetId: $targetId, title: $title, subtitle: $subtitle, metadata: $metadata, createdAt: $createdAt)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$ActivityLogModelImpl &&
            (identical(other.logId, logId) || other.logId == logId) &&
            (identical(other.type, type) || other.type == type) &&
            (identical(other.actorUid, actorUid) ||
                other.actorUid == actorUid) &&
            (identical(other.actorRole, actorRole) ||
                other.actorRole == actorRole) &&
            (identical(other.targetType, targetType) ||
                other.targetType == targetType) &&
            (identical(other.targetId, targetId) ||
                other.targetId == targetId) &&
            (identical(other.title, title) || other.title == title) &&
            (identical(other.subtitle, subtitle) ||
                other.subtitle == subtitle) &&
            const DeepCollectionEquality().equals(other._metadata, _metadata) &&
            (identical(other.createdAt, createdAt) ||
                other.createdAt == createdAt));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType,
      logId,
      type,
      actorUid,
      actorRole,
      targetType,
      targetId,
      title,
      subtitle,
      const DeepCollectionEquality().hash(_metadata),
      createdAt);

  /// Create a copy of ActivityLogModel
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  @pragma('vm:prefer-inline')
  _$$ActivityLogModelImplCopyWith<_$ActivityLogModelImpl> get copyWith =>
      __$$ActivityLogModelImplCopyWithImpl<_$ActivityLogModelImpl>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$ActivityLogModelImplToJson(
      this,
    );
  }
}

abstract class _ActivityLogModel implements ActivityLogModel {
  const factory _ActivityLogModel(
          {required final String logId,
          required final String type,
          final String? actorUid,
          final String? actorRole,
          final String? targetType,
          final String? targetId,
          required final String title,
          final String? subtitle,
          final Map<String, dynamic>? metadata,
          @TimestampConverter() required final DateTime createdAt}) =
      _$ActivityLogModelImpl;

  factory _ActivityLogModel.fromJson(Map<String, dynamic> json) =
      _$ActivityLogModelImpl.fromJson;

  /// Document id (auto-generated by Firestore `.add()`).
  @override
  String get logId;

  /// One of [ActivityLogType] names. Stored as a string so the
  /// schema is forward-compatible with future types.
  @override
  String get type;

  /// Uid of the user that performed the action. For self-service
  /// events (login, registration) this is the user themselves.
  @override
  String? get actorUid;

  /// "buyer" / "streetSeller" / "admin" — denormalised so the
  /// Activity Logs screen can filter without a join.
  @override
  String? get actorRole;

  /// "user" / "order" / "listing" / "category" — what the action
  /// touched.
  @override
  String? get targetType;

  /// Id of the affected target.
  @override
  String? get targetId;

  /// Human-readable headline shown on the Activity Logs screen.
  @override
  String get title;

  /// One-line subtitle shown below the title.
  @override
  String? get subtitle;

  /// Free-form metadata bag for the Admin Logs detail sheet.
  /// Always optional so old docs without it still deserialize.
  @override
  Map<String, dynamic>? get metadata;
  @override
  @TimestampConverter()
  DateTime get createdAt;

  /// Create a copy of ActivityLogModel
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  _$$ActivityLogModelImplCopyWith<_$ActivityLogModelImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
